---
name: "Modulator"
---

Voyage\\Modulator\\ModularPage:
  base_class: 'Voyage\\Modulator\\PageModule'
  write_content: true

Symbiote\\GridFieldExtensions\\GridFieldOrderableRows:
  extensions:
    - 'Voyage\\Modulator\\PageModuleExtension'
