Voyage\\Modulator\\ModularPage:
  base_class: 'Voyage\Modulator\PageModule'
  write_content: true

Voyage\\Modulator\\GridFieldOrderableRows:
  extensions:
    - 'Voyage\Modulator\PageModuleExtension'
