mappings:
  ModularPage: Voyage\Modulator\ModularPage
  ModularPageController: Voyage\Modulator\ModularPageController
  PageModule: Voyage\Modulator\PageModule
  GridFieldConfig_ModuleEditor: Voyage\Modulator\GridFieldConfig_ModuleEditor
  PageModuleExtension: Voyage\Modulator\PageModuleExtension
  GridFieldModuleColumns: Voyage\Modulator\GridFieldModuleColumns
